# Generated by Django 4.1.7 on 2023-04-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_position_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='position',
            name='longitude',
        ),
        migrations.AddField(
            model_name='position',
            name='coli',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.coli'),
            preserve_default=False,
        ),
    ]
