# Generated by Django 4.1.7 on 2023-04-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_position_latitude_remove_position_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='coli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coli', to='api.coli'),
        ),
    ]
